packages:
  - packages/*

catalog:
  "@algorandfoundation/algokit-utils": ^9.1.0
  "@eslint/js": ^9.18.0
  "@stablelib/base64": ^2.0.1
  "@stablelib/utf8": ^2.0.1
  "@types/node": ^20.9.0
  chalk: ^5.3.0
  concurrently: ^9.1.0
  eslint: ^9.16.0
  eslint-config-prettier: ^9.1.0
  globals: ^15.13.0
  prettier: ^3.4.2
  "react-icons": ^5.4.0
  shx: ^0.3.4
  tsx: 4.19.2
  typescript: ^5.7.2
  typescript-eslint: ^8.18.0
  vite: ^6.0.3
  vite-plugin-dts: ^4.3.0
  vite-tsconfig-paths: ^5.1.4
  vitest: ^2.1.8
