name: "Release"

on:
  push:
    branches:
      - beta
      - main

concurrency:
  group: release-${{ github.ref_name }}
  cancel-in-progress: true # ensure only one release workflow runs per branch (e.g., "release-beta" or "release-main")

permissions:
  contents: write # to be able to publish a github release
  issues: write # to be able to comment on released issues
  packages: write  # to be able to publish packages
  pull-requests: write # to be able to comment on released pull requests

jobs:
  release_chains:
    name: "Release - @kibisis/chains"
    uses: ./.github/workflows/publish_release.yml
    with:
      package_dir: "chains"
      package_name: "@kibisis/chains"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_PACKAGES_ACCESS_TOKEN }}

  release_utilities:
    name: "Release - @kibisis/utilities"
    needs: [release_chains]
    uses: ./.github/workflows/publish_release.yml
    with:
      package_dir: "utilities"
      package_name: "@kibisis/utilities"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_PACKAGES_ACCESS_TOKEN }}
